# Generated by Django 4.2.3 on 2023-07-31 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_alter_email_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
